### ISSUE TITLE
new UI

### ISSUE THREAD

**Issue by michalassif** [shenkarlab/TheAverageEve#10]
@mushon @NoamRom89 @Basicben 

בהמשך לביקורת בשיעור, ניסינו ליצור חווית משתמש חדשה המדגישה ומשתמשת בציר המרכזי שלנו
כל האלמנטים (כותרת, כפתורים ואיור) נכנסים לבמה כשהם חצויים לשניים. הבנים מלמטה הבנות מלמעלה.
בכל סצינה האלמנט האיורי המרכזי יעלם לתוך המרכז ובמקומו תופיע הדאטה

מצ"ב הדגמות לסוגי דאטה שונים

נשמח לחוות דעת (ממוצעות חחח) על מנת להתקדם.

![mock_up-01](https://cloud.githubusercontent.com/assets/9408495/5593090/56aa2d2a-91fd-11e4-9080-db0c32377cdd.jpg)
![mock_up-02](https://cloud.githubusercontent.com/assets/9408495/5593092/56ab4ec6-91fd-11e4-9e0d-ac2b62938bbe.jpg)
![mock_up-03](https://cloud.githubusercontent.com/assets/9408495/5593091/56aadebe-91fd-11e4-9cf7-4a5aacd9a8f8.jpg)
![mock_up-04](https://cloud.githubusercontent.com/assets/9408495/5593093/56b3eff4-91fd-11e4-9d0d-3e1608a04204.jpg)

**Comment by Basicben** [comment]
לעניות דעתי זה נראה ממש טוב אבל מה אני מבין..
על פנוי זה נראה בר ביצוע מבחינתו למעט סלייד מס' 3 בו צריכים לחלק את הדאטה לשני צבעים שונים.
לא ירדתי לעומק של זה אז אל תתפסו אותי במילה.

תעלו ותצליחו ושתזכו לבנים זכרים.

**Comment by polinekes** [comment]
הי מושון , נשמח לדעתך
@mushon

**Comment by mushon** [comment]
סורי, אני לא כלכך אוהב את החיתוך של האיור ״באוויר״ זה נראה לי מוזר ולא כ״כ עובד עם השפה שלכם. גם הבחירה הטיפוגרפית שלכם לא ממש עובדת לדעתי עם השפה האיורית והצבעונית (המוצלחת) היו לכם סטייל-טיילז? אין לי בעיה שתציגו שני כיווני סטייל טיילז שמבוססים על השפה האיורית וההחלטה של הקונטרסט, שעוברים יפה יחד, אבל אני מרגיש כרגע שהשפה הגרפית והממשקית עדיין לא באותה רמה.
בואו תעלו סטייל טיילז עם כמה אייטמים ממשקיים וטקסטואלים, עם דוגמאות לשילוב כותרות ואיור וכפתורים וכאלה וגם עם מילות מפתח (איזה ערכים אנחנו מנסים לתקשר) ומילות נגד (מאיזה ערכים אנחנו מנסים להתרחק) כדי שאוכל לתת לכם פידבק יותר מדוייק.

**Comment by polinekes** [comment]
הי מושון - תודה על התגובה

אין בעיה שנעשה סטייל טייז ואכן נעשה. **הבעיה העיקרית שמקשה עלינו** והביא אותנו להחלטות שאתה ראית הם השיקולים הבאים:
**1.כותרות**
 האם הכותרות שקשורות לשני המינים צריכים להיות באמצע ובמידה שלא- למה שהם היו בצד האחד ולא בשני. האם אנחנו יכולים להוריד דאגה זו ממחשבותנו ולהקיד שזה בצד ימין כי כך השפה העברית?.

ובמידה ושזה כן חייב להיות באמצע - צבע אחד שלישי יכול לעבוד- אבל אז אנחנו עולים על הציר ומטשטשים אותו(לכן עשינו 2 פונטים שונים) וקיבלנו ממכם פידבק שלא להעלות על הציר האמצעי

**2. כפתורים**
אותו כנ״ל. אם הדאטה פותח מידע שקשור לשני הצדדים - אפשר שהכפתור עצמו יהיה רק בצד אחד? ויציג דאטה סימטרי בשני הצדדים.
ושוב נשאלת השאלה למה הגברי ולא הנשי

**
אם אנחנו מחליטים שאנחנו משתחררים מקבלי מאיזה צד הדאטה מגיעה** ואומרים שזה תמיד אקראי ,  ושרק האיור והדאטה
יהיו נאמנים לציר האמצעי ולחצי חצי - יהיה לנו יותר קל
**
מה אתה אומר - אפשר שלא הכל יהיה טואטאלי?

**Comment by mushon** [comment]
בהחלט אפשר,
מה שחשוב זה ליצר גריד עקבי עם חוקיות ברורה ואם יש בה מורכבות כזו או אחרת חשוב שהיא תהיה מוגדרת ופשוטה כדי שההחלטות המבניות לא יתחרו זו בזו. 
בהצלחה!

**Comment by polinekes** [comment]
הי כולם 
שני סוגי עיצוב וסגנון לרכיבי האתר שלנו 

מוזמנים להגיב מה יותר מוצא חן בעינכם ולמה (אפשר גם דברים מסוימים שני האפשרויות)

שבוע טוב

@michalassif @mushon @Basicben @NoamRom89 
**אפשרות א**
![style tile-01](https://cloud.githubusercontent.com/assets/6918730/5604068/07c8b0ca-93ae-11e4-8e5a-154a77d4fcd8.png)

**אפשרות ב**

![style tile-02](https://cloud.githubusercontent.com/assets/6918730/5604069/07c8e98c-93ae-11e4-8205-99cc34112579.png)

**Comment by michalassif** [comment]
מיפוי נתונים על פי שלבים

![default](https://cloud.githubusercontent.com/assets/9408495/5605196/57c817f8-93f6-11e4-8de1-77ff6fc7f40a.jpg)
![2](https://cloud.githubusercontent.com/assets/9408495/5605197/57ca65bc-93f6-11e4-864c-997c783ec12c.jpg)

**Comment by michalassif** [comment]
![mock_up3](https://cloud.githubusercontent.com/assets/9408495/5665891/6748e48e-9764-11e4-846c-1b8f75b1eee7.jpg)
@Basicben @polinekes @NoamRom89

**Comment by polinekes** [comment]
מייכל תותחית! טנקס
בהמשך יעלו האיורים החדשים 

@Basicben @michalassif

**Comment by polinekes** [comment]
![hospital_new](https://cloud.githubusercontent.com/assets/6918730/5691831/b776802c-98e2-11e4-9517-e532ebe126ce.png)

![new_playground](https://cloud.githubusercontent.com/assets/6918730/5691832/c6193174-98e2-11e4-9924-12655fd511fc.png)
@michalassif

**Comment by Basicben** [comment]
http://shenkar.html5-book.co.il/2014-2015/html5/dev_33/eve/index2

בנתיים
